name: "Package deploy"
on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Deploy
              run: mvn deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}