name: "Package deploy"
on:
    push:
        branches:
            - 'master'
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checking out code base
              uses: actions/checkout@v2
            - name: Setting up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Deploying
              run: mvn deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}